pid: tmp/pids/thin.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []
environment: development
max_persistent_conns: 512
servers: 1
threaded: true
daemonize: false
port: 5500
tag: erp
