default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: erp_development
  username: ashish.agrawal
  password:

testing:
  <<: *default
  database: erp_testing

test:
  <<: *default
  database: erp_test

production:
  <<: *default
  database: erp_production
  password: <%= ENV['ERP_DATABASE_PASSWORD'] %>
